// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6MQ_LsqoSKl7iBchO6kMwonhJHbRXvvs',
    appId: '1:433429123250:web:a9925dcbb53db9747fb9ab',
    messagingSenderId: '433429123250',
    projectId: 'com-example-flutter-appli-1',
    authDomain: 'com-example-flutter-appli-1.firebaseapp.com',
    storageBucket: 'com-example-flutter-appli-1.firebasestorage.app',
    measurementId: 'G-X7QSSFZT6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmHzMiyb3oYAbuNu_wKmXFlI--Eql3xW8',
    appId: '1:433429123250:android:5bdacb7713dbdbf47fb9ab',
    messagingSenderId: '433429123250',
    projectId: 'com-example-flutter-appli-1',
    storageBucket: 'com-example-flutter-appli-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn3pDvXdc0s0myGPKFW7IXHt1bBDtGaEA',
    appId: '1:433429123250:ios:555dd8654b9f7c9f7fb9ab',
    messagingSenderId: '433429123250',
    projectId: 'com-example-flutter-appli-1',
    storageBucket: 'com-example-flutter-appli-1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn3pDvXdc0s0myGPKFW7IXHt1bBDtGaEA',
    appId: '1:433429123250:ios:555dd8654b9f7c9f7fb9ab',
    messagingSenderId: '433429123250',
    projectId: 'com-example-flutter-appli-1',
    storageBucket: 'com-example-flutter-appli-1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6MQ_LsqoSKl7iBchO6kMwonhJHbRXvvs',
    appId: '1:433429123250:web:cf23ebdc1098d38d7fb9ab',
    messagingSenderId: '433429123250',
    projectId: 'com-example-flutter-appli-1',
    authDomain: 'com-example-flutter-appli-1.firebaseapp.com',
    storageBucket: 'com-example-flutter-appli-1.firebasestorage.app',
    measurementId: 'G-BQ1L1MTWBC',
  );
}
